In [ ]:
import numpy as np

x = 10
y = 5
z = 9
vec = [x,y,z]
vec2d = [ vec, [x*2,y*2,z*2]]
print(vec)
vec_np = np.array(vec)
vec2d_np = np.array(vec2d)
print(vec_np)
print(vec2d_np)
vec_np
print(vec2d_np.reshape(6))

In [23]:
a = np.array([0,1,2,3,4,5])

In [25]:
 a *2

array([ 0,  2,  4,  6,  8, 10])

In [28]:
ar = np.array([[10,10],[3,8]])
ab = np.array([[7,8],[9,9]])

ar + ab

array([[17, 18],
       [12, 17]])

In [31]:
ar

array([[10, 10],
       [ 3,  8]])

In [30]:
ar.dot(ab)

array([[160, 170],
       [ 93,  96]])

In [32]:
ab

array([[7, 8],
       [9, 9]])

In [33]:
a1 = np.arange(25)

In [34]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
d2 = a1.reshape(5,5)

In [36]:
d2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [50]:
d2[:3,:4]

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])